### ISSUE TITLE
Issue-completed frontend intialization

### ISSUE THREAD

**Issue by hitosisasaki** [hitosisasaki/prospark#106]
Automated Review Comments
Issues in cli/src/helper/projectSetup/setup_frontend.ts:
  - (4, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (32, 'Hardcoded string found')
  - (33, 'Hardcoded string found')

**Comment by satomichru** [comment]
I got it.
