### ISSUE TITLE
Issue-updated backend template

### ISSUE THREAD

**Issue by hitosisasaki** [hitosisasaki/prospark#114]
Automated Review Comments
Issues in cli/src/data/backend_templates.ts:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (70, 'Hardcoded string found')
  - (77, 'Line exceeds 80 characters')
  - (77, 'Hardcoded string found')
  - (79, 'Hardcoded string found')
  - (88, 'Hardcoded string found')

**Comment by satomichru** [comment]
I got it.
