### ISSUE TITLE
Issue-fix: updated setup_frontend

### ISSUE THREAD

**Issue by hitosisasaki** [hitosisasaki/prospark#39]
Automated Review Comments
Issues in cli/src/helper/projectSetup/setup_frontend.ts:
  - (1, 'Line exceeds 80 characters')
  - (2, 'Hardcoded string found')
  - (3, 'Line exceeds 80 characters')
  - (15, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (24, 'Line exceeds 80 characters')
  - (34, 'Hardcoded string found')
Issues in cli/src/util/logger.ts:
  - (1, 'Hardcoded string found')

**Comment by satomichru** [comment]
I got it.
