### ISSUE TITLE
Issue-fix: added major changes to setup frontend

### ISSUE THREAD

**Issue by hitosisasaki** [hitosisasaki/prospark#41]
Automated Review Comments
Issues in cli/src/data/template.ts:
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
Issues in cli/src/helper/file-manager.ts:
  - (1, 'Line exceeds 80 characters')
Issues in cli/src/helper/installDependencies.ts:
  - (1, 'Line exceeds 80 characters')
  - (4, 'Hardcoded string found')
Issues in cli/src/helper/projectSetup/setup_frontend.ts:
  - (5, 'Line exceeds 80 characters')
  - (5, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (33, 'Line exceeds 80 characters')
  - (40, 'Line exceeds 80 characters')
  - (43, 'Hardcoded string found')
  - (45, 'Hardcoded string found')
  - (47, 'Line exceeds 80 characters')
  - (47, 'Hardcoded string found')
  - (48, 'Line exceeds 80 characters')
  - (48, 'Hardcoded string found')
  - (52, 'Hardcoded string found')
  - (53, 'Hardcoded string found')
  - (55, 'Hardcoded string found')
  - (57, 'Line exceeds 80 characters')
  - (58, 'Line exceeds 80 characters')
  - (61, 'Hardcoded string found')
  - (62, 'Hardcoded string found')
  - (64, 'Hardcoded string found')
  - (66, 'Line exceeds 80 characters')
  - (67, 'Line exceeds 80 characters')
  - (67, 'Hardcoded string found')
  - (71, 'Line exceeds 80 characters')
  - (72, 'Line exceeds 80 characters')
  - (74, 'Line exceeds 80 characters')
  - (74, 'Hardcoded string found')
  - (80, 'Line exceeds 80 characters')
  - (96, 'Hardcoded string found')
  - (98, 'Hardcoded string found')
  - (100, 'Line exceeds 80 characters')
  - (100, 'Hardcoded string found')
  - (101, 'Line exceeds 80 characters')
  - (101, 'Hardcoded string found')
  - (102, 'Line exceeds 80 characters')
  - (102, 'Hardcoded string found')
  - (108, 'Hardcoded string found')
  - (110, 'Line exceeds 80 characters')
  - (110, 'Hardcoded string found')
  - (111, 'Line exceeds 80 characters')
  - (111, 'Hardcoded string found')
  - (112, 'Line exceeds 80 characters')
  - (112, 'Hardcoded string found')
  - (113, 'Line exceeds 80 characters')
  - (113, 'Hardcoded string found')
  - (118, 'Line exceeds 80 characters')
  - (118, 'Hardcoded string found')
  - (119, 'Hardcoded string found')
  - (120, 'Hardcoded string found')
  - (127, 'Line exceeds 80 characters')
Issues in cli/src/templates/client/js_support/vanilla/index.html:
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
Issues in cli/src/templates/client/js_support/vanilla/main.js:
  - (8, 'Hardcoded string found')
  - (9, 'Line exceeds 80 characters')
  - (9, 'Hardcoded string found')
Issues in cli/src/templates/client/ts_support/vanilla/index.html:
  - (3, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
Issues in cli/src/templates/client/ts_support/vanilla/package-lock.json:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (18, 'Line exceeds 80 characters')
  - (18, 'Hardcoded string found')
  - (19, 'Line exceeds 80 characters')
  - (19, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
  - (29, 'Hardcoded string found')
  - (33, 'Hardcoded string found')
  - (34, 'Line exceeds 80 characters')
  - (34, 'Hardcoded string found')
  - (35, 'Line exceeds 80 characters')
  - (35, 'Hardcoded string found')
  - (36, 'Hardcoded string found')
  - (39, 'Hardcoded string found')
  - (40, 'Hardcoded string found')
  - (41, 'Hardcoded string found')
  - (42, 'Hardcoded string found')
  - (44, 'Hardcoded string found')
  - (45, 'Hardcoded string found')
  - (49, 'Hardcoded string found')
  - (50, 'Hardcoded string found')
  - (51, 'Line exceeds 80 characters')
  - (51, 'Hardcoded string found')
  - (52, 'Hardcoded string found')
  - (53, 'Hardcoded string found')
  - (54, 'Hardcoded string found')
  - (55, 'Hardcoded string found')
  - (57, 'Hardcoded string found')
  - (58, 'Hardcoded string found')
  - (60, 'Hardcoded string found')
  - (86, 'Hardcoded string found')
  - (87, 'Line exceeds 80 characters')
  - (87, 'Hardcoded string found')
  - (88, 'Line exceeds 80 characters')
  - (88, 'Hardcoded string found')
  - (89, 'Hardcoded string found')
  - (92, 'Hardcoded string found')
  - (93, 'Hardcoded string found')
  - (94, 'Hardcoded string found')
  - (95, 'Hardcoded string found')
  - (97, 'Hardcoded string found')
  - (98, 'Hardcoded string found')
  - (102, 'Hardcoded string found')
  - (103, 'Line exceeds 80 characters')
  - (103, 'Hardcoded string found')
  - (104, 'Line exceeds 80 characters')
  - (104, 'Hardcoded string found')
  - (105, 'Hardcoded string found')
  - (108, 'Hardcoded string found')
  - (109, 'Hardcoded string found')
  - (110, 'Hardcoded string found')
  - (111, 'Hardcoded string found')
  - (113, 'Hardcoded string found')
  - (114, 'Hardcoded string found')
  - (118, 'Hardcoded string found')
  - (119, 'Line exceeds 80 characters')
  - (119, 'Hardcoded string found')
  - (120, 'Line exceeds 80 characters')
  - (120, 'Hardcoded string found')
  - (121, 'Hardcoded string found')
  - (124, 'Hardcoded string found')
  - (125, 'Hardcoded string found')
  - (126, 'Hardcoded string found')
  - (127, 'Hardcoded string found')
  - (129, 'Hardcoded string found')
  - (130, 'Hardcoded string found')
  - (134, 'Hardcoded string found')
  - (135, 'Line exceeds 80 characters')
  - (135, 'Hardcoded string found')
  - (136, 'Line exceeds 80 characters')
  - (136, 'Hardcoded string found')
  - (137, 'Hardcoded string found')
  - (140, 'Hardcoded string found')
  - (141, 'Hardcoded string found')
  - (142, 'Hardcoded string found')
  - (143, 'Hardcoded string found')
  - (145, 'Hardcoded string found')
  - (146, 'Hardcoded string found')
  - (150, 'Hardcoded string found')
  - (151, 'Line exceeds 80 characters')
  - (151, 'Hardcoded string found')
  - (152, 'Line exceeds 80 characters')
  - (152, 'Hardcoded string found')
  - (153, 'Hardcoded string found')
  - (156, 'Hardcoded string found')
  - (157, 'Hardcoded string found')
  - (158, 'Hardcoded string found')
  - (159, 'Hardcoded string found')
  - (161, 'Hardcoded string found')
  - (162, 'Hardcoded string found')
  - (166, 'Hardcoded string found')
  - (167, 'Line exceeds 80 characters')
  - (167, 'Hardcoded string found')
  - (168, 'Line exceeds 80 characters')
  - (168, 'Hardcoded string found')
  - (169, 'Hardcoded string found')
  - (172, 'Hardcoded string found')
  - (173, 'Hardcoded string found')
  - (174, 'Hardcoded string found')
  - (175, 'Hardcoded string found')
  - (177, 'Hardcoded string found')
  - (178, 'Hardcoded string found')
  - (182, 'Hardcoded string found')
  - (183, 'Line exceeds 80 characters')
  - (183, 'Hardcoded string found')
  - (184, 'Line exceeds 80 characters')
  - (184, 'Hardcoded string found')
  - (185, 'Hardcoded string found')
  - (188, 'Hardcoded string found')
  - (189, 'Hardcoded string found')
  - (190, 'Hardcoded string found')
  - (191, 'Hardcoded string found')
  - (193, 'Hardcoded string found')
  - (194, 'Hardcoded string found')
  - (198, 'Hardcoded string found')
  - (199, 'Line exceeds 80 characters')
  - (199, 'Hardcoded string found')
  - (200, 'Line exceeds 80 characters')
  - (200, 'Hardcoded string found')
  - (201, 'Hardcoded string found')
  - (204, 'Hardcoded string found')
  - (205, 'Hardcoded string found')
  - (206, 'Hardcoded string found')
  - (207, 'Hardcoded string found')
  - (209, 'Hardcoded string found')
  - (210, 'Hardcoded string found')
  - (214, 'Hardcoded string found')
  - (215, 'Line exceeds 80 characters')
  - (215, 'Hardcoded string found')
  - (216, 'Line exceeds 80 characters')
  - (216, 'Hardcoded string found')
  - (217, 'Hardcoded string found')
  - (218, 'Hardcoded string found')
  - (220, 'Hardcoded string found')
  - (221, 'Hardcoded string found')
  - (222, 'Hardcoded string found')
  - (223, 'Hardcoded string found')
  - (225, 'Hardcoded string found')
  - (226, 'Hardcoded string found')
  - (230, 'Hardcoded string found')
  - (231, 'Line exceeds 80 characters')
  - (231, 'Hardcoded string found')
  - (232, 'Line exceeds 80 characters')
  - (232, 'Hardcoded string found')
  - (233, 'Hardcoded string found')
  - (236, 'Hardcoded string found')
  - (237, 'Hardcoded string found')
  - (238, 'Hardcoded string found')
  - (239, 'Hardcoded string found')
  - (241, 'Hardcoded string found')
  - (242, 'Hardcoded string found')
  - (246, 'Hardcoded string found')
  - (247, 'Line exceeds 80 characters')
  - (247, 'Hardcoded string found')
  - (248, 'Line exceeds 80 characters')
  - (248, 'Hardcoded string found')
  - (249, 'Hardcoded string found')
  - (252, 'Hardcoded string found')
  - (253, 'Hardcoded string found')
  - (254, 'Hardcoded string found')
  - (255, 'Hardcoded string found')
  - (257, 'Hardcoded string found')
  - (258, 'Hardcoded string found')
  - (262, 'Hardcoded string found')
  - (263, 'Line exceeds 80 characters')
  - (263, 'Hardcoded string found')
  - (264, 'Line exceeds 80 characters')
  - (264, 'Hardcoded string found')
  - (265, 'Hardcoded string found')
  - (268, 'Hardcoded string found')
  - (269, 'Hardcoded string found')
  - (270, 'Hardcoded string found')
  - (271, 'Hardcoded string found')
  - (273, 'Hardcoded string found')
  - (274, 'Hardcoded string found')
  - (278, 'Hardcoded string found')
  - (279, 'Line exceeds 80 characters')
  - (279, 'Hardcoded string found')
  - (280, 'Line exceeds 80 characters')
  - (280, 'Hardcoded string found')
  - (281, 'Hardcoded string found')
  - (284, 'Hardcoded string found')
  - (285, 'Hardcoded string found')
  - (286, 'Hardcoded string found')
  - (287, 'Hardcoded string found')
  - (289, 'Hardcoded string found')
  - (290, 'Hardcoded string found')
  - (294, 'Hardcoded string found')
  - (295, 'Line exceeds 80 characters')
  - (295, 'Hardcoded string found')
  - (296, 'Line exceeds 80 characters')
  - (296, 'Hardcoded string found')
  - (297, 'Hardcoded string found')
  - (300, 'Hardcoded string found')
  - (301, 'Hardcoded string found')
  - (302, 'Hardcoded string found')
  - (303, 'Hardcoded string found')
  - (305, 'Hardcoded string found')
  - (306, 'Hardcoded string found')
  - (310, 'Hardcoded string found')
  - (311, 'Line exceeds 80 characters')
  - (311, 'Hardcoded string found')
  - (312, 'Line exceeds 80 characters')
  - (312, 'Hardcoded string found')
  - (313, 'Hardcoded string found')
  - (316, 'Hardcoded string found')
  - (317, 'Hardcoded string found')
  - (318, 'Hardcoded string found')
  - (319, 'Hardcoded string found')
  - (321, 'Hardcoded string found')
  - (322, 'Hardcoded string found')
  - (326, 'Hardcoded string found')
  - (327, 'Line exceeds 80 characters')
  - (327, 'Hardcoded string found')
  - (328, 'Line exceeds 80 characters')
  - (328, 'Hardcoded string found')
  - (329, 'Hardcoded string found')
  - (332, 'Hardcoded string found')
  - (333, 'Hardcoded string found')
  - (334, 'Hardcoded string found')
  - (335, 'Hardcoded string found')
  - (337, 'Hardcoded string found')
  - (338, 'Hardcoded string found')
  - (342, 'Hardcoded string found')
  - (343, 'Line exceeds 80 characters')
  - (343, 'Hardcoded string found')
  - (344, 'Line exceeds 80 characters')
  - (344, 'Hardcoded string found')
  - (345, 'Hardcoded string found')
  - (348, 'Hardcoded string found')
  - (349, 'Hardcoded string found')
  - (350, 'Hardcoded string found')
  - (351, 'Hardcoded string found')
  - (353, 'Hardcoded string found')
  - (354, 'Hardcoded string found')
  - (358, 'Hardcoded string found')
  - (359, 'Line exceeds 80 characters')
  - (359, 'Hardcoded string found')
  - (360, 'Line exceeds 80 characters')
  - (360, 'Hardcoded string found')
  - (361, 'Hardcoded string found')
  - (364, 'Hardcoded string found')
  - (365, 'Hardcoded string found')
  - (366, 'Hardcoded string found')
  - (369, 'Hardcoded string found')
  - (370, 'Hardcoded string found')
  - (374, 'Hardcoded string found')
  - (375, 'Line exceeds 80 characters')
  - (375, 'Hardcoded string found')
  - (376, 'Line exceeds 80 characters')
  - (376, 'Hardcoded string found')
  - (377, 'Hardcoded string found')
  - (380, 'Hardcoded string found')
  - (381, 'Hardcoded string found')
  - (382, 'Hardcoded string found')
  - (385, 'Hardcoded string found')
  - (386, 'Hardcoded string found')
  - (390, 'Hardcoded string found')
  - (391, 'Line exceeds 80 characters')
  - (391, 'Hardcoded string found')
  - (392, 'Line exceeds 80 characters')
  - (392, 'Hardcoded string found')
  - (393, 'Hardcoded string found')
  - (396, 'Hardcoded string found')
  - (397, 'Hardcoded string found')
  - (398, 'Hardcoded string found')
  - (401, 'Hardcoded string found')
  - (402, 'Hardcoded string found')
  - (406, 'Hardcoded string found')
  - (407, 'Hardcoded string found')
  - (408, 'Line exceeds 80 characters')
  - (408, 'Hardcoded string found')
  - (409, 'Hardcoded string found')
  - (410, 'Hardcoded string found')
  - (411, 'Hardcoded string found')
  - (412, 'Hardcoded string found')
  - (413, 'Hardcoded string found')
  - (415, 'Hardcoded string found')
  - (416, 'Hardcoded string found')
  - (420, 'Hardcoded string found')
  - (421, 'Line exceeds 80 characters')
  - (421, 'Hardcoded string found')
  - (422, 'Line exceeds 80 characters')
  - (422, 'Hardcoded string found')
  - (423, 'Hardcoded string found')
  - (426, 'Hardcoded string found')
  - (427, 'Hardcoded string found')
  - (428, 'Line exceeds 80 characters')
  - (428, 'Hardcoded string found')
  - (429, 'Hardcoded string found')
  - (430, 'Hardcoded string found')
  - (433, 'Hardcoded string found')
  - (434, 'Hardcoded string found')
  - (438, 'Hardcoded string found')
  - (439, 'Line exceeds 80 characters')
  - (439, 'Hardcoded string found')
  - (440, 'Line exceeds 80 characters')
  - (440, 'Hardcoded string found')
  - (441, 'Hardcoded string found')
  - (442, 'Hardcoded string found')
  - (443, 'Hardcoded string found')
  - (445, 'Hardcoded string found')
  - (446, 'Hardcoded string found')
  - (450, 'Hardcoded string found')
  - (451, 'Hardcoded string found')
  - (452, 'Line exceeds 80 characters')
  - (452, 'Hardcoded string found')
  - (453, 'Hardcoded string found')
  - (454, 'Hardcoded string found')
  - (455, 'Hardcoded string found')
  - (457, 'Hardcoded string found')
  - (458, 'Hardcoded string found')
  - (462, 'Hardcoded string found')
  - (463, 'Line exceeds 80 characters')
  - (463, 'Hardcoded string found')
  - (464, 'Line exceeds 80 characters')
  - (464, 'Hardcoded string found')
  - (465, 'Hardcoded string found')
  - (468, 'Hardcoded string found')
  - (469, 'Line exceeds 80 characters')
  - (469, 'Hardcoded string found')
  - (470, 'Line exceeds 80 characters')
  - (470, 'Hardcoded string found')
  - (471, 'Hardcoded string found')
  - (474, 'Hardcoded string found')
  - (475, 'Hardcoded string found')
  - (476, 'Line exceeds 80 characters')
  - (476, 'Hardcoded string found')
  - (477, 'Hardcoded string found')
  - (478, 'Hardcoded string found')
  - (480, 'Hardcoded string found')
  - (481, 'Hardcoded string found')
  - (484, 'Hardcoded string found')
  - (485, 'Hardcoded string found')
  - (488, 'Hardcoded string found')
  - (489, 'Hardcoded string found')
  - (490, 'Hardcoded string found')
  - (493, 'Hardcoded string found')
  - (494, 'Hardcoded string found')
  - (498, 'Hardcoded string found')
  - (499, 'Hardcoded string found')
  - (500, 'Line exceeds 80 characters')
  - (500, 'Hardcoded string found')
  - (501, 'Hardcoded string found')
  - (502, 'Hardcoded string found')
  - (507, 'Hardcoded string found')
  - (508, 'Hardcoded string found')
  - (510, 'Hardcoded string found')
  - (511, 'Hardcoded string found')
  - (515, 'Hardcoded string found')
  - (516, 'Hardcoded string found')
  - (517, 'Line exceeds 80 characters')
  - (517, 'Hardcoded string found')
  - (518, 'Hardcoded string found')
  - (519, 'Hardcoded string found')
  - (520, 'Hardcoded string found')
  - (522, 'Hardcoded string found')
  - (523, 'Hardcoded string found')
  - (525, 'Hardcoded string found')
  - (526, 'Hardcoded string found')
  - (530, 'Hardcoded string found')
  - (531, 'Line exceeds 80 characters')
  - (531, 'Hardcoded string found')
  - (532, 'Line exceeds 80 characters')
  - (532, 'Hardcoded string found')
  - (533, 'Hardcoded string found')
  - (534, 'Hardcoded string found')
  - (535, 'Hardcoded string found')
  - (539, 'Hardcoded string found')
  - (540, 'Line exceeds 80 characters')
  - (540, 'Hardcoded string found')
  - (541, 'Line exceeds 80 characters')
  - (541, 'Hardcoded string found')
  - (542, 'Hardcoded string found')
  - (543, 'Hardcoded string found')
  - (544, 'Hardcoded string found')
  - (546, 'Hardcoded string found')
  - (547, 'Hardcoded string found')
  - (551, 'Hardcoded string found')
  - (552, 'Line exceeds 80 characters')
  - (552, 'Hardcoded string found')
  - (553, 'Line exceeds 80 characters')
  - (553, 'Hardcoded string found')
  - (554, 'Hardcoded string found')
  - (555, 'Hardcoded string found')
  - (556, 'Hardcoded string found')
  - (557, 'Hardcoded string found')
  - (559, 'Hardcoded string found')
  - (560, 'Hardcoded string found')
  - (564, 'Hardcoded string found')
  - (565, 'Hardcoded string found')
  - (566, 'Line exceeds 80 characters')
  - (566, 'Hardcoded string found')
  - (567, 'Hardcoded string found')
  - (568, 'Hardcoded string found')
  - (569, 'Hardcoded string found')
  - (570, 'Hardcoded string found')
  - (571, 'Hardcoded string found')
  - (572, 'Hardcoded string found')
  - (574, 'Hardcoded string found')
  - (575, 'Hardcoded string found')
  - (577, 'Hardcoded string found')
  - (578, 'Hardcoded string found')
  - (580, 'Hardcoded string found')
  - (581, 'Hardcoded string found')
  - (583, 'Hardcoded string found')
  - (585, 'Hardcoded string found')
  - (586, 'Hardcoded string found')
  - (587, 'Hardcoded string found')
  - (588, 'Hardcoded string found')
  - (589, 'Hardcoded string found')
  - (591, 'Hardcoded string found')
  - (593, 'Hardcoded string found')
  - (595, 'Hardcoded string found')
  - (596, 'Hardcoded string found')
  - (598, 'Hardcoded string found')
  - (599, 'Hardcoded string found')
  - (601, 'Hardcoded string found')
  - (602, 'Hardcoded string found')
  - (604, 'Hardcoded string found')
  - (605, 'Hardcoded string found')
  - (607, 'Hardcoded string found')
  - (608, 'Hardcoded string found')
  - (613, 'Hardcoded string found')
  - (615, 'Hardcoded string found')
  - (616, 'Line exceeds 80 characters')
  - (616, 'Hardcoded string found')
  - (617, 'Line exceeds 80 characters')
  - (617, 'Hardcoded string found')
  - (618, 'Hardcoded string found')
  - (619, 'Hardcoded string found')
  - (622, 'Hardcoded string found')
  - (623, 'Line exceeds 80 characters')
  - (623, 'Hardcoded string found')
  - (624, 'Line exceeds 80 characters')
  - (624, 'Hardcoded string found')
  - (625, 'Hardcoded string found')
  - (626, 'Hardcoded string found')
  - (628, 'Hardcoded string found')
  - (629, 'Hardcoded string found')
  - (630, 'Hardcoded string found')
  - (631, 'Line exceeds 80 characters')
  - (631, 'Hardcoded string found')
  - (632, 'Hardcoded string found')
  - (633, 'Hardcoded string found')
  - (659, 'Hardcoded string found')
  - (660, 'Line exceeds 80 characters')
  - (660, 'Hardcoded string found')
  - (661, 'Line exceeds 80 characters')
  - (661, 'Hardcoded string found')
  - (662, 'Hardcoded string found')
  - (663, 'Hardcoded string found')
  - (666, 'Hardcoded string found')
  - (667, 'Line exceeds 80 characters')
  - (667, 'Hardcoded string found')
  - (668, 'Line exceeds 80 characters')
  - (668, 'Hardcoded string found')
  - (669, 'Hardcoded string found')
  - (670, 'Hardcoded string found')
  - (673, 'Hardcoded string found')
  - (674, 'Line exceeds 80 characters')
  - (674, 'Hardcoded string found')
  - (675, 'Line exceeds 80 characters')
  - (675, 'Hardcoded string found')
  - (676, 'Hardcoded string found')
  - (677, 'Hardcoded string found')
  - (680, 'Hardcoded string found')
  - (681, 'Line exceeds 80 characters')
  - (681, 'Hardcoded string found')
  - (682, 'Line exceeds 80 characters')
  - (682, 'Hardcoded string found')
  - (683, 'Hardcoded string found')
  - (684, 'Hardcoded string found')
  - (687, 'Hardcoded string found')
  - (688, 'Line exceeds 80 characters')
  - (688, 'Hardcoded string found')
  - (689, 'Line exceeds 80 characters')
  - (689, 'Hardcoded string found')
  - (690, 'Hardcoded string found')
  - (691, 'Hardcoded string found')
  - (694, 'Hardcoded string found')
  - (695, 'Line exceeds 80 characters')
  - (695, 'Hardcoded string found')
  - (696, 'Line exceeds 80 characters')
  - (696, 'Hardcoded string found')
  - (697, 'Hardcoded string found')
  - (698, 'Hardcoded string found')
  - (701, 'Hardcoded string found')
  - (702, 'Line exceeds 80 characters')
  - (702, 'Hardcoded string found')
  - (703, 'Line exceeds 80 characters')
  - (703, 'Hardcoded string found')
  - (704, 'Hardcoded string found')
  - (705, 'Hardcoded string found')
  - (708, 'Hardcoded string found')
  - (709, 'Line exceeds 80 characters')
  - (709, 'Hardcoded string found')
  - (710, 'Line exceeds 80 characters')
  - (710, 'Hardcoded string found')
  - (711, 'Hardcoded string found')
  - (712, 'Hardcoded string found')
  - (715, 'Hardcoded string found')
  - (716, 'Line exceeds 80 characters')
  - (716, 'Hardcoded string found')
  - (717, 'Line exceeds 80 characters')
  - (717, 'Hardcoded string found')
  - (718, 'Hardcoded string found')
  - (719, 'Hardcoded string found')
  - (722, 'Hardcoded string found')
  - (723, 'Line exceeds 80 characters')
  - (723, 'Hardcoded string found')
  - (724, 'Line exceeds 80 characters')
  - (724, 'Hardcoded string found')
  - (725, 'Hardcoded string found')
  - (726, 'Hardcoded string found')
  - (729, 'Hardcoded string found')
  - (730, 'Line exceeds 80 characters')
  - (730, 'Hardcoded string found')
  - (731, 'Line exceeds 80 characters')
  - (731, 'Hardcoded string found')
  - (732, 'Hardcoded string found')
  - (733, 'Hardcoded string found')
  - (736, 'Hardcoded string found')
  - (737, 'Line exceeds 80 characters')
  - (737, 'Hardcoded string found')
  - (738, 'Line exceeds 80 characters')
  - (738, 'Hardcoded string found')
  - (739, 'Hardcoded string found')
  - (740, 'Hardcoded string found')
  - (743, 'Hardcoded string found')
  - (744, 'Line exceeds 80 characters')
  - (744, 'Hardcoded string found')
  - (745, 'Line exceeds 80 characters')
  - (745, 'Hardcoded string found')
  - (746, 'Hardcoded string found')
  - (747, 'Hardcoded string found')
  - (750, 'Hardcoded string found')
  - (751, 'Line exceeds 80 characters')
  - (751, 'Hardcoded string found')
  - (752, 'Line exceeds 80 characters')
  - (752, 'Hardcoded string found')
  - (753, 'Hardcoded string found')
  - (754, 'Hardcoded string found')
  - (757, 'Hardcoded string found')
  - (758, 'Line exceeds 80 characters')
  - (758, 'Hardcoded string found')
  - (759, 'Line exceeds 80 characters')
  - (759, 'Hardcoded string found')
  - (760, 'Hardcoded string found')
  - (761, 'Hardcoded string found')
  - (764, 'Hardcoded string found')
  - (765, 'Line exceeds 80 characters')
  - (765, 'Hardcoded string found')
  - (766, 'Line exceeds 80 characters')
  - (766, 'Hardcoded string found')
  - (767, 'Hardcoded string found')
  - (768, 'Hardcoded string found')
  - (771, 'Hardcoded string found')
  - (772, 'Line exceeds 80 characters')
  - (772, 'Hardcoded string found')
  - (773, 'Line exceeds 80 characters')
  - (773, 'Hardcoded string found')
  - (774, 'Hardcoded string found')
  - (775, 'Hardcoded string found')
  - (778, 'Hardcoded string found')
  - (779, 'Line exceeds 80 characters')
  - (779, 'Hardcoded string found')
  - (780, 'Line exceeds 80 characters')
  - (780, 'Hardcoded string found')
  - (781, 'Hardcoded string found')
  - (782, 'Hardcoded string found')
  - (785, 'Hardcoded string found')
  - (786, 'Line exceeds 80 characters')
  - (786, 'Hardcoded string found')
  - (787, 'Line exceeds 80 characters')
  - (787, 'Hardcoded string found')
  - (788, 'Hardcoded string found')
  - (789, 'Hardcoded string found')
  - (792, 'Hardcoded string found')
  - (793, 'Line exceeds 80 characters')
  - (793, 'Hardcoded string found')
  - (794, 'Line exceeds 80 characters')
  - (794, 'Hardcoded string found')
  - (795, 'Hardcoded string found')
  - (796, 'Hardcoded string found')
  - (798, 'Hardcoded string found')
  - (799, 'Hardcoded string found')
  - (800, 'Hardcoded string found')
  - (801, 'Line exceeds 80 characters')
  - (801, 'Hardcoded string found')
  - (802, 'Hardcoded string found')
  - (803, 'Hardcoded string found')
  - (806, 'Hardcoded string found')
  - (807, 'Line exceeds 80 characters')
  - (807, 'Hardcoded string found')
  - (808, 'Line exceeds 80 characters')
  - (808, 'Hardcoded string found')
  - (809, 'Hardcoded string found')
  - (811, 'Hardcoded string found')
  - (812, 'Hardcoded string found')
  - (813, 'Hardcoded string found')
  - (814, 'Line exceeds 80 characters')
  - (814, 'Hardcoded string found')
  - (815, 'Hardcoded string found')
  - (816, 'Hardcoded string found')
  - (821, 'Hardcoded string found')
  - (822, 'Line exceeds 80 characters')
  - (822, 'Hardcoded string found')
  - (823, 'Line exceeds 80 characters')
  - (823, 'Hardcoded string found')
  - (824, 'Hardcoded string found')
  - (825, 'Hardcoded string found')
  - (826, 'Hardcoded string found')
  - (829, 'Hardcoded string found')
  - (830, 'Hardcoded string found')
  - (831, 'Hardcoded string found')
  - (832, 'Line exceeds 80 characters')
  - (832, 'Hardcoded string found')
  - (833, 'Hardcoded string found')
  - (836, 'Hardcoded string found')
  - (837, 'Line exceeds 80 characters')
  - (837, 'Hardcoded string found')
  - (838, 'Line exceeds 80 characters')
  - (838, 'Hardcoded string found')
  - (839, 'Hardcoded string found')
  - (841, 'Hardcoded string found')
  - (842, 'Hardcoded string found')
  - (843, 'Line exceeds 80 characters')
  - (843, 'Hardcoded string found')
  - (844, 'Line exceeds 80 characters')
  - (844, 'Hardcoded string found')
  - (845, 'Hardcoded string found')
  - (847, 'Hardcoded string found')
  - (848, 'Hardcoded string found')
  - (849, 'Hardcoded string found')
  - (850, 'Line exceeds 80 characters')
  - (850, 'Hardcoded string found')
  - (851, 'Hardcoded string found')
  - (852, 'Hardcoded string found')
  - (853, 'Hardcoded string found')
  - (854, 'Hardcoded string found')
  - (858, 'Hardcoded string found')
  - (859, 'Hardcoded string found')
  - (860, 'Hardcoded string found')
  - (861, 'Line exceeds 80 characters')
  - (861, 'Hardcoded string found')
  - (862, 'Hardcoded string found')
  - (863, 'Hardcoded string found')
  - (869, 'Hardcoded string found')
  - (870, 'Hardcoded string found')
  - (871, 'Hardcoded string found')
  - (872, 'Line exceeds 80 characters')
  - (872, 'Hardcoded string found')
  - (873, 'Hardcoded string found')
  - (874, 'Hardcoded string found')
  - (875, 'Hardcoded string found')
  - (879, 'Hardcoded string found')
  - (880, 'Line exceeds 80 characters')
  - (880, 'Hardcoded string found')
  - (881, 'Line exceeds 80 characters')
  - (881, 'Hardcoded string found')
  - (882, 'Hardcoded string found')
  - (885, 'Hardcoded string found')
  - (886, 'Line exceeds 80 characters')
  - (886, 'Hardcoded string found')
  - (887, 'Line exceeds 80 characters')
  - (887, 'Hardcoded string found')
  - (888, 'Hardcoded string found')
  - (890, 'Hardcoded string found')
  - (891, 'Hardcoded string found')
  - (892, 'Line exceeds 80 characters')
  - (892, 'Hardcoded string found')
  - (893, 'Line exceeds 80 characters')
  - (893, 'Hardcoded string found')
  - (894, 'Hardcoded string found')
  - (896, 'Hardcoded string found')
  - (897, 'Hardcoded string found')
  - (898, 'Hardcoded string found')
  - (899, 'Line exceeds 80 characters')
  - (899, 'Hardcoded string found')
  - (900, 'Hardcoded string found')
  - (901, 'Hardcoded string found')
  - (902, 'Hardcoded string found')
  - (903, 'Hardcoded string found')
  - (904, 'Hardcoded string found')
  - (905, 'Hardcoded string found')
  - (906, 'Hardcoded string found')
Issues in cli/src/templates/client/ts_support/vanilla/package.json:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
Issues in cli/src/templates/client/ts_support/vanilla/public/vite.svg:
  - (2, 'Line exceeds 80 characters')
  - (2, 'Hardcoded string found')
Issues in cli/src/templates/client/ts_support/vanilla/src/counter.ts:
  - (8, 'Hardcoded string found')
Issues in cli/src/templates/client/ts_support/vanilla/tsconfig.json:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (20, 'Hardcoded string found')

**Comment by satomichru** [comment]
I got it.
