### ISSUE TITLE
Issue-feat: added react template

### ISSUE THREAD

**Issue by hitosisasaki** [hitosisasaki/prospark#43]
Automated Review Comments
Issues in cli/src/data/template.ts:
  - (9, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
Issues in cli/src/helper/projectSetup/setup_frontend.ts:
  - (4, 'Line exceeds 80 characters')
  - (5, 'Line exceeds 80 characters')
  - (6, 'Line exceeds 80 characters')
  - (7, 'Line exceeds 80 characters')
  - (8, 'Line exceeds 80 characters')
  - (11, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
Issues in cli/src/templates/client/js_support/react/index.html:
  - (3, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
Issues in cli/src/templates/client/js_support/react/package.json:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
Issues in cli/src/templates/client/js_support/react/public/vite.svg:
  - (2, 'Line exceeds 80 characters')
  - (2, 'Hardcoded string found')
Issues in cli/src/templates/client/js_support/react/src/App.jsx:
  - (2, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
Issues in cli/src/templates/client/js_support/react/src/assets/react.svg:
  - (2, 'Line exceeds 80 characters')
  - (2, 'Hardcoded string found')
Issues in cli/src/templates/client/js_support/react/src/main.jsx:
  - (2, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
Issues in cli/src/templates/client/js_support/react/vite.config.js:
  - (2, 'Hardcoded string found')

**Comment by satomichru** [comment]
I got it.
