### ISSUE TITLE
Issue-feat: added react ( Js ) + css module setup

### ISSUE THREAD

**Issue by hitosisasaki** [hitosisasaki/prospark#52]
Automated Review Comments
Issues in cli/src/data/template.ts:
  - (1, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
Issues in cli/src/helper/projectSetup/base_setup.ts:
  - (6, 'Line exceeds 80 characters')
  - (14, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
  - (29, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
  - (37, 'Line exceeds 80 characters')
  - (38, 'Line exceeds 80 characters')
  - (40, 'Line exceeds 80 characters')
  - (40, 'Hardcoded string found')
  - (48, 'Line exceeds 80 characters')
  - (48, 'Hardcoded string found')
  - (51, 'Line exceeds 80 characters')
  - (51, 'Hardcoded string found')
  - (58, 'Hardcoded string found')
  - (62, 'Line exceeds 80 characters')
  - (63, 'Line exceeds 80 characters')
  - (65, 'Line exceeds 80 characters')
  - (70, 'Hardcoded string found')
  - (74, 'Hardcoded string found')
  - (86, 'Hardcoded string found')
  - (90, 'Line exceeds 80 characters')
Issues in cli/src/helper/projectSetup/setup_frontend.ts:
  - (2, 'Line exceeds 80 characters')
  - (2, 'Hardcoded string found')
  - (5, 'Line exceeds 80 characters')
  - (5, 'Hardcoded string found')
  - (15, 'Line exceeds 80 characters')
  - (16, 'Line exceeds 80 characters')
  - (18, 'Line exceeds 80 characters')
  - (26, 'Line exceeds 80 characters')
  - (27, 'Line exceeds 80 characters')
  - (44, 'Line exceeds 80 characters')
  - (46, 'Line exceeds 80 characters')
  - (49, 'Line exceeds 80 characters')
  - (65, 'Line exceeds 80 characters')

**Comment by satokihanada** [comment]
I got it.
