### ISSUE TITLE
Issue-feat: added react (Ts) support and scaffolding logic

### ISSUE THREAD

**Issue by hitosisasaki** [hitosisasaki/prospark#56]
Automated Review Comments
Issues in cli/src/helper/projectSetup/base_setup.ts:
  - (2, 'Line exceeds 80 characters')
  - (3, 'Line exceeds 80 characters')
  - (5, 'Hardcoded string found')
  - (6, 'Line exceeds 80 characters')
  - (6, 'Hardcoded string found')
  - (16, 'Line exceeds 80 characters')
  - (16, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (29, 'Line exceeds 80 characters')
  - (32, 'Hardcoded string found')
  - (37, 'Hardcoded string found')
  - (42, 'Hardcoded string found')
  - (47, 'Line exceeds 80 characters')
Issues in cli/src/helper/projectSetup/setup_frontend.ts:
  - (11, 'Line exceeds 80 characters')
  - (11, 'Hardcoded string found')
  - (15, 'Line exceeds 80 characters')
  - (15, 'Hardcoded string found')
  - (18, 'Line exceeds 80 characters')
  - (18, 'Hardcoded string found')
  - (23, 'Line exceeds 80 characters')
Issues in cli/src/templates/client/ts_support/react/src/App.tsx:
  - (2, 'Hardcoded string found')

**Comment by satokihanada** [comment]
I got it.
