### ISSUE TITLE
Issue-feat: added script to setup svelte and tailwindcss

### ISSUE THREAD

**Issue by hitosisasaki** [hitosisasaki/prospark#64]
Automated Review Comments
Issues in cli/src/data/template.ts:
  - (2, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
Issues in cli/src/helper/projectSetup/base_setup.ts:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (5, 'Line exceeds 80 characters')
  - (6, 'Line exceeds 80 characters')
  - (7, 'Line exceeds 80 characters')
  - (8, 'Hardcoded string found')
  - (14, 'Line exceeds 80 characters')
  - (19, 'Line exceeds 80 characters')
  - (19, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
  - (29, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
  - (31, 'Hardcoded string found')
  - (32, 'Hardcoded string found')
  - (33, 'Hardcoded string found')
  - (47, 'Line exceeds 80 characters')
  - (51, 'Hardcoded string found')
  - (52, 'Line exceeds 80 characters')
  - (52, 'Hardcoded string found')
  - (60, 'Hardcoded string found')
  - (65, 'Hardcoded string found')
  - (68, 'Hardcoded string found')
  - (70, 'Line exceeds 80 characters')
  - (74, 'Line exceeds 80 characters')
  - (80, 'Line exceeds 80 characters')
  - (81, 'Line exceeds 80 characters')
  - (84, 'Hardcoded string found')
  - (88, 'Hardcoded string found')
  - (100, 'Hardcoded string found')
  - (104, 'Line exceeds 80 characters')
Issues in cli/src/helper/projectSetup/setup_frontend.ts:
  - (14, 'Line exceeds 80 characters')
  - (16, 'Line exceeds 80 characters')
  - (17, 'Line exceeds 80 characters')
  - (24, 'Line exceeds 80 characters')
  - (25, 'Line exceeds 80 characters')
  - (32, 'Line exceeds 80 characters')
  - (33, 'Line exceeds 80 characters')
  - (50, 'Line exceeds 80 characters')
  - (52, 'Line exceeds 80 characters')
  - (55, 'Line exceeds 80 characters')
  - (57, 'Line exceeds 80 characters')
  - (73, 'Line exceeds 80 characters')
Issues in cli/src/templates/client/js_support/svelte/src/App.svelte:
  - (10, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (23, 'Line exceeds 80 characters')
Issues in cli/src/templates/client/js_support/svelte/src/lib/Counter.svelte:
  - (6, 'Hardcoded string found')

**Comment by satokihanada** [comment]
I got it.
