### ISSUE TITLE
Issue-completed svelte(js) + tailwindcss support

### ISSUE THREAD

**Issue by hitosisasaki** [hitosisasaki/prospark#68]
Automated Review Comments
Issues in cli/src/data/template.ts:
  - (7, 'Hardcoded string found')
Issues in cli/src/helper/projectSetup/base_setup.ts:
  - (3, 'Hardcoded string found')
  - (5, 'Line exceeds 80 characters')
  - (6, 'Line exceeds 80 characters')
  - (11, 'Line exceeds 80 characters')
  - (12, 'Line exceeds 80 characters')
  - (13, 'Hardcoded string found')
Issues in cli/src/helper/projectSetup/setup_frontend.ts:
  - (24, 'Line exceeds 80 characters')
  - (25, 'Line exceeds 80 characters')

**Comment by satokihanada** [comment]
I got it.
