### ISSUE TITLE
Issue-ref: added method to get indexhtml file script extension

### ISSUE THREAD

**Issue by hitosisasaki** [hitosisasaki/prospark#70]
Automated Review Comments
Issues in cli/src/helper/projectSetup/base_setup.ts:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (5, 'Line exceeds 80 characters')
  - (6, 'Line exceeds 80 characters')
  - (7, 'Line exceeds 80 characters')
  - (8, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (29, 'Hardcoded string found')
  - (32, 'Hardcoded string found')
  - (35, 'Hardcoded string found')
  - (38, 'Hardcoded string found')
  - (41, 'Hardcoded string found')
  - (52, 'Hardcoded string found')
  - (58, 'Line exceeds 80 characters')
  - (66, 'Hardcoded string found')
  - (67, 'Hardcoded string found')
  - (68, 'Hardcoded string found')
  - (69, 'Hardcoded string found')
  - (70, 'Hardcoded string found')
  - (73, 'Hardcoded string found')
  - (74, 'Hardcoded string found')
  - (75, 'Hardcoded string found')
  - (76, 'Hardcoded string found')
  - (77, 'Hardcoded string found')
  - (78, 'Hardcoded string found')
  - (79, 'Hardcoded string found')
  - (80, 'Hardcoded string found')
  - (81, 'Hardcoded string found')
  - (82, 'Hardcoded string found')
  - (96, 'Line exceeds 80 characters')
  - (101, 'Line exceeds 80 characters')
  - (101, 'Hardcoded string found')
  - (102, 'Hardcoded string found')
  - (106, 'Hardcoded string found')
  - (107, 'Hardcoded string found')
  - (108, 'Hardcoded string found')
  - (109, 'Hardcoded string found')
  - (111, 'Hardcoded string found')
  - (112, 'Hardcoded string found')
  - (113, 'Hardcoded string found')
  - (114, 'Hardcoded string found')
  - (115, 'Hardcoded string found')
  - (122, 'Line exceeds 80 characters')
  - (123, 'Line exceeds 80 characters')
  - (125, 'Line exceeds 80 characters')
  - (125, 'Hardcoded string found')
  - (128, 'Line exceeds 80 characters')
  - (128, 'Hardcoded string found')
  - (136, 'Hardcoded string found')
  - (139, 'Line exceeds 80 characters')
  - (139, 'Hardcoded string found')
  - (146, 'Hardcoded string found')
  - (151, 'Line exceeds 80 characters')
  - (152, 'Line exceeds 80 characters')
  - (155, 'Line exceeds 80 characters')
  - (160, 'Hardcoded string found')
  - (164, 'Hardcoded string found')
  - (176, 'Hardcoded string found')
  - (180, 'Line exceeds 80 characters')
  - (188, 'Hardcoded string found')
  - (191, 'Hardcoded string found')
  - (193, 'Line exceeds 80 characters')
  - (197, 'Line exceeds 80 characters')
  - (198, 'Line exceeds 80 characters')
  - (199, 'Hardcoded string found')
  - (208, 'Hardcoded string found')
  - (211, 'Line exceeds 80 characters')
  - (212, 'Line exceeds 80 characters')
  - (213, 'Line exceeds 80 characters')
  - (216, 'Hardcoded string found')
  - (222, 'Hardcoded string found')
  - (223, 'Line exceeds 80 characters')
  - (223, 'Hardcoded string found')
  - (224, 'Hardcoded string found')
  - (233, 'Hardcoded string found')
  - (236, 'Line exceeds 80 characters')
  - (237, 'Line exceeds 80 characters')
  - (238, 'Line exceeds 80 characters')
Issues in cli/src/helper/projectSetup/setup_frontend.ts:
  - (1, 'Line exceeds 80 characters')
  - (6, 'Hardcoded string found')
  - (7, 'Line exceeds 80 characters')
  - (17, 'Hardcoded string found')
  - (28, 'Line exceeds 80 characters')
  - (28, 'Hardcoded string found')
  - (83, 'Line exceeds 80 characters')
  - (84, 'Line exceeds 80 characters')
  - (97, 'Line exceeds 80 characters')
  - (117, 'Line exceeds 80 characters')
  - (117, 'Hardcoded string found')
  - (120, 'Line exceeds 80 characters')
  - (120, 'Hardcoded string found')
  - (124, 'Line exceeds 80 characters')
  - (124, 'Hardcoded string found')
  - (127, 'Line exceeds 80 characters')
  - (127, 'Hardcoded string found')
  - (137, 'Line exceeds 80 characters')
  - (138, 'Line exceeds 80 characters')
  - (140, 'Line exceeds 80 characters')
  - (153, 'Line exceeds 80 characters')
  - (154, 'Line exceeds 80 characters')
  - (156, 'Line exceeds 80 characters')
  - (170, 'Line exceeds 80 characters')
  - (172, 'Line exceeds 80 characters')
  - (175, 'Line exceeds 80 characters')
  - (180, 'Line exceeds 80 characters')
  - (195, 'Line exceeds 80 characters')
  - (203, 'Line exceeds 80 characters')
  - (204, 'Line exceeds 80 characters')
  - (221, 'Line exceeds 80 characters')
  - (223, 'Line exceeds 80 characters')
  - (226, 'Line exceeds 80 characters')
  - (242, 'Line exceeds 80 characters')
  - (250, 'Line exceeds 80 characters')
  - (251, 'Line exceeds 80 characters')
  - (268, 'Line exceeds 80 characters')
  - (270, 'Line exceeds 80 characters')
  - (274, 'Line exceeds 80 characters')

**Comment by satomichru** [comment]
I got it.
