### ISSUE TITLE
Issue-updated base_setup for svelte

### ISSUE THREAD

**Issue by hitosisasaki** [hitosisasaki/prospark#76]
Automated Review Comments
Issues in cli/src/helper/projectSetup/base_setup.ts:
  - (5, 'Hardcoded string found')
  - (6, 'Line exceeds 80 characters')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (13, 'Hardcoded string found')

**Comment by satokihanada** [comment]
I got it.
