### ISSUE TITLE
Issue-added a function to check for package version

### ISSUE THREAD

**Issue by hitosisasaki** [hitosisasaki/prospark#8]
Automated Review Comments
Issues in cli/helper/checkPackageVersion.ts:
  - (2, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (29, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
Issues in cli/util/renderTitle.ts:
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')

**Comment by satokihanada** [comment]
I got it.
