### ISSUE TITLE
Issue-updated file-manager

### ISSUE THREAD

**Issue by hitosisasaki** [hitosisasaki/prospark#98]
Automated Review Comments
Issues in cli/src/helper/file-manager.ts:
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (63, 'Hardcoded string found')
  - (81, 'Hardcoded string found')
  - (102, 'Line exceeds 80 characters')
  - (105, 'Line exceeds 80 characters')
  - (149, 'Line exceeds 80 characters')
  - (157, 'Hardcoded string found')
  - (158, 'Hardcoded string found')
  - (165, 'Hardcoded string found')
  - (168, 'Hardcoded string found')
  - (172, 'Line exceeds 80 characters')
  - (181, 'Line exceeds 80 characters')
  - (191, 'Hardcoded string found')
  - (192, 'Hardcoded string found')
  - (200, 'Hardcoded string found')
  - (203, 'Hardcoded string found')
  - (240, 'Hardcoded string found')
  - (241, 'Hardcoded string found')
  - (257, 'Hardcoded string found')
  - (260, 'Hardcoded string found')
  - (279, 'Hardcoded string found')
  - (280, 'Hardcoded string found')
  - (296, 'Hardcoded string found')
  - (299, 'Hardcoded string found')
  - (305, 'Line exceeds 80 characters')
  - (310, 'Line exceeds 80 characters')
  - (330, 'Line exceeds 80 characters')
  - (347, 'Line exceeds 80 characters')
  - (358, 'Line exceeds 80 characters')

**Comment by satomichru** [comment]
I got it.
